# # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# name: "JS Actions"

# on: [push]

# jobs:
#   action:
#     runs-on: "ubuntu-latest"
#     steps:
#       - uses: actions/checkout@v2

#       - name: "install hello-action dependencies"
#         run: npm install
#         working-directory: ./.github/actions/hello-world

#       - name: "hello-action"
#         uses: ./.github/actions/hello-world
#         with:
#           first-greeting: "Learning Lab User"

name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "install hello-action dependencies"
        run: npm install
        working-directory: ./.github/actions/hello-world
      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: "install joke-action dependencies"
        run: npm install
        working-directory: ./.github/actions/joke-action
      - name: ha-ha
        uses: ./.github/actions/joke-action

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}
