# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "JS Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: "install hello-action dependencies"
        run: npm ci
        working-directory: ./.github/actions/hello-world

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          first-greeting: "Learning Lab User"
